name: Initialize and Start Workflow

on: [push]

jobs:
  setup-and-execute:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up environment
      run: |
        chmod +x ./init.sh
        ./init.sh

    - name: Execute script
      env:
        HEADLESS_MODE: 'true'  # Set environment variable for headless mode
      run: |
        chmod +x ./start.sh
        ./start.sh
